// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.busyboxes.redwatcher.domain;

import ch.busyboxes.redwatcher.domain.ServerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ServerDataOnDemand_Roo_Configurable {
    
    declare @type: ServerDataOnDemand: @Configurable;
    
}
